### ISSUE TITLE
Bug: Login for same user with multiple browsers does not work as expected

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#100]
1. User should have a Login id	
2. Open the Tradebull site with a Browser
3. Provide Email and password
4. Click on Login button
5. Open tradebull in another browser and try logging in with Same credentials as above

Expectd
The User should either be logged out from the older browser or should not be allowed to login with the new browser window

Actual
The user is able to work with both logins

**Comment by kshitijbhardwaj** [comment]
@anmoldeep0123 Need to handle in backend

**Comment by theheapdump** [comment]
@bevanamit  - sessions are not cross browser. do we need to enforce only one session per person !!!

**Comment by bevanamit** [comment]
multiple tabs in same browser was ok, but having multiple sessions across browsers, is it ok ? changes from multiple sessions parallely needs to be taken care ...

**Comment by theheapdump** [comment]
why not ?? 

can;t u open facebook linked in two browsers at the same time ??

**Comment by bevanamit** [comment]
We can open... Can you open kite on 2 browsers and operate... It logs one
fellow out.

**Comment by theheapdump** [comment]
ok i can fix this

**Comment by bevanamit** [comment]
tested
