### ISSUE TITLE
Bug: Getting only OK message when doing Confirm OTP with valid OTP

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#101]
Register new user, (using the same browser have done multiple times by closing the tabs)
Provide details and clink on Register
On OTP screen provide proper OTP and click on button confirm OTP

Expected
The User should be taken to the Profile screen

Actual
The User is just shown OK message in UI and in the Network I see the response as below
{"redirectTo":null,"status":"ERROR","status_message":""}

![image](https://user-images.githubusercontent.com/5267251/99430452-5d45f680-292f-11eb-9b55-a04919496f53.png)

**Comment by kshitijbhardwaj** [comment]
@anmoldeep0123 fix in backend

**Comment by theheapdump** [comment]
@bevanamit , @kshitijbhardwaj 
this is a result of Issue # 95 . They are linked.

**Comment by theheapdump** [comment]
Fixed

**Comment by bevanamit** [comment]
Issue not observed again
