### ISSUE TITLE
Bug: Back button UI errors 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#102]
1. Open tradebull
2. Navigate to Register screen by clicking on the Register link 
3. Provide valid inputs and click on register
4. when the user is taken to OTP screen click on browser back button 5

Expected
The back button should get back the User to the Main Tradebull Page

Actual
Issue the User is logged in and is able to see dashboard

**Comment by kshitijbhardwaj** [comment]
This issue will be fixed when we fix the session management

**Comment by theheapdump** [comment]
@bevanamit  - test this

**Comment by bevanamit** [comment]
tested
