### ISSUE TITLE
Bug: Send Again link in OTP screen should be greyed out as making it invisilbe does not give User any indication that they can resend OTP

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#103]
1. Open tradebull
2. Navigate to Register screen by clicking on the Register link 
3. Provide proper details and click on Register
4. Check if Send Again link is visible immediately when the OTP screen is loaded

Expected
The Send Again link should be greyed out and should be enabled only after a time gap, and the time remaining should be visible as it user has to know.

Actual
currently user does not know if he will have send again link and also doesnt know when it will get enabled

**Comment by kshitijbhardwaj** [comment]
I am showing this details in success toast. that he can try again after 1 min

**Comment by theheapdump** [comment]
based on @kshitijbhardwaj  latest comments -> moving to @bevanamit  as fixed

**Comment by bevanamit** [comment]
Send again vanishes
![image](https://user-images.githubusercontent.com/5267251/99682766-a0c27100-2aa5-11eb-9654-b40b10dfab43.png)

**Comment by kshitijbhardwaj** [comment]
CLosing as per discussion with team
