### ISSUE TITLE
Bug: Unknown Error encountered

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#104]
Tried registering same details with tradebull and clicked on register

![image](https://user-images.githubusercontent.com/5267251/99529904-9aa99300-29c6-11eb-9af4-afd5b488e0c9.png)

**Comment by theheapdump** [comment]
Register 
as well login is totally fine.

Please test this now 

give valid values in key and secret

**Comment by theheapdump** [comment]
@bevanamit

**Comment by theheapdump** [comment]
6o1xtbz3t0u1dg6i


ocpwos5jcc822587izk5wmebsgfs8rad
