### ISSUE TITLE
Bug: Invalid email not validate

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#107]
1. Open tradebull
2. Navigate to Register screen by clicking on the Register link
3. Provide invalid email id "testmailid@sdsd..ss

Expected
There should be proper error message stating the email id is invalid

Actual 
No Error

**Comment by kshitijbhardwaj** [comment]
This is already a known issue.

**Comment by bevanamit** [comment]
Oh ok, if it's already fixed then please mark it I will check again

**Comment by bevanamit** [comment]
tested
![image](https://user-images.githubusercontent.com/5267251/99685346-7faf4f80-2aa8-11eb-987a-f89f84ecba24.png)
