### ISSUE TITLE
Bug: Related to "https://github.com/anmoldeep0123/kite-webapp/issues/95" the message stated is not correct when User logs in after closing windows without confirming OTP

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#114]
User open the Tradebull application
Click on Register
Provide details required, click on Register
On the OTP screen, close the window
Try logging in with the registered user

Expected
On login the OTP screen should be shown
The OTP should be confirmed and the next screens should be shown

Actual
User is let in without OTP confirmation

The messages in screen should be updated.
![image](https://user-images.githubusercontent.com/5267251/99663254-4ff24e80-2a8c-11eb-8330-91efcbe2fdee.png)

**Comment by kshitijbhardwaj** [comment]
Its there below as Let's confirm your Email that should be fine

**Comment by theheapdump** [comment]
:)

**Comment by theheapdump** [comment]
@kshitijbhardwaj  🥇

**Comment by theheapdump** [comment]
@bevanamit @kshitijbhardwaj  please sort this out

**Comment by kshitijbhardwaj** [comment]
Change this message as per our discussion

**Comment by bevanamit** [comment]
We are now showing below image both the times

![image](https://user-images.githubusercontent.com/5267251/99910903-be4a4180-2d16-11eb-803d-84ad045ef13c.png)
