### ISSUE TITLE
Bug: Date in profile settings is allowing 6 digits

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#115]
![image](https://user-images.githubusercontent.com/5267251/99663794-2ab21000-2a8d-11eb-999c-470c4d90673e.png)

The DOB should be at least 10yrs old as per today's date when the user is filling out the form.

**Comment by kshitijbhardwaj** [comment]
there is already an issue related to this date validation
Will be handled there

**Comment by theheapdump** [comment]
Closing this as linked to  - another issue

**Comment by bevanamit** [comment]
Linked to which issue?

**Comment by theheapdump** [comment]
It already says in the ticket above referenced number #56
