### ISSUE TITLE
Bug: OTP confirmation failed for digits starting with "0" (zero)

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#116]
![image](https://user-images.githubusercontent.com/5267251/99664250-e83d0300-2a8d-11eb-8333-9afb9300064e.png)

**Comment by theheapdump** [comment]
@kshitijbhardwaj - please send OTP as string from UI

**Comment by kshitijbhardwaj** [comment]
Fixed

**Comment by theheapdump** [comment]
@bevanamit if u hit this again let me know.

**Comment by theheapdump** [comment]
OTP now will never start with 0

**Comment by bevanamit** [comment]
Not able to check as OTP are not coming starting with 0

**Comment by theheapdump** [comment]
they will never come now

**Comment by theheapdump** [comment]
Closing this
