### ISSUE TITLE
User Story 12 - Create a DOC in Wiki for instances on AWS & GCP.

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#12]
private key,
user name,
su password
sample ssh connectivity command

**Comment by theheapdump** [comment]
@bevanamit , can we close this today.

**Comment by bevanamit** [comment]
@anmoldeep0123 not able to attach file to iwki

**Comment by theheapdump** [comment]
@bevanamit - added a gdrive LOC - please add GCP info as well. thanks

**Comment by theheapdump** [comment]
Thanks @bevanamit
