### ISSUE TITLE
Implement Referral code & handle all issues around Referral Code | Backend Dev

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#121]
![image](https://user-images.githubusercontent.com/5267251/99682328-1aa62a80-2aa5-11eb-9ec8-fa0af881ad47.png)

**Comment by theheapdump** [comment]
Fixed.

**Comment by theheapdump** [comment]
@bevanamit startup referral code is TRADMIN1234

**Comment by theheapdump** [comment]
Closing as fixed and tested
