### ISSUE TITLE
Bug: When there is issue with registration for same email/phone being used we are able to click register without limit

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#122]
![image](https://user-images.githubusercontent.com/5267251/99686730-e2551b00-2aa9-11eb-911d-336accc5d58f.png)

**Comment by theheapdump** [comment]
@kshitijbhardwaj  should disable the button after first error from backend unless email_id / phone is changed

**Comment by theheapdump** [comment]
@kshitijbhardwaj  let's fix this.

**Comment by kshitijbhardwaj** [comment]
For this issue also if there is some error in register i am clearing the password and confirm password as in login page we had decided. This disables the register button also as login button untill user puts password and confirm password again.
This is simple and consistent too.

**Comment by bevanamit** [comment]
![Uploading image.png…]()

**Comment by bevanamit** [comment]
tested
