### ISSUE TITLE
Bug: Registration of a long email address was shown invalid - maxlength 100 restrcition

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#124]
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz@mailinator.com

but textbox did not show any issue... @anmoldeep0123 @kshitijbhardwaj should we decide on length

![image](https://user-images.githubusercontent.com/5267251/99694177-23512d80-2ab2-11eb-880d-01aa820cfd8a.png)

**Comment by theheapdump** [comment]
yes let us be practical and stop @ max length - 50 both backend and front end . @kshitijbhardwaj  @bevanamit

**Comment by theheapdump** [comment]
@kshitijbhardwaj  let's fix this also

**Comment by theheapdump** [comment]
can we close this today ... @kshitijbhardwaj

**Comment by bevanamit** [comment]
Typed : abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxasdsadsds@mailinator.com for email address....please correct...check the image....if there is a certain defined length for email lets go with that
![image](https://user-images.githubusercontent.com/5267251/100543103-30210e80-3274-11eb-8209-3fe8cd4f37aa.png)

**Comment by theheapdump** [comment]
If. backend is throwing an error - we should be OK

**Comment by theheapdump** [comment]
This is low priority and can be taken if any customer reports . for now . backend error is enough !!! Closing this  @bevanamit
