### ISSUE TITLE
Bug: We should allow only alphabets in firstname and lastname

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#125]
![image](https://user-images.githubusercontent.com/5267251/99695692-dbcba100-2ab3-11eb-8b10-9cbe139e3988.png)

**Comment by theheapdump** [comment]
with. a max length as well @kshitijbhardwaj

**Comment by kshitijbhardwaj** [comment]
Name can have both alphabets and numbers so i have added validation for not allowing special characters for First name
Last name should n't be required field many ppl don't have last name like me. Hence removed required validation.

**Comment by bevanamit** [comment]
tested
