### ISSUE TITLE
Bug: we should allow only alphanumeric values for Broker Client ID

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#126]
![image](https://user-images.githubusercontent.com/5267251/99696007-395fed80-2ab4-11eb-8488-a5979e6629a8.png)

**Comment by bevanamit** [comment]
@kshitijbhardwaj @anmoldeep0123 we should also restrict the characters to 30 max...as no broker client id will go beyond that i believe

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/99793599-ea1acb00-2b4e-11eb-9e9b-27dfbc35e4d5.png)


zerodha has a max length of 6 for username they do not allow typing more than 6 

let us follow same

**Comment by theheapdump** [comment]
@bevanamit @kshitijbhardwaj

**Comment by bevanamit** [comment]
tested
