### ISSUE TITLE
Bug: Broker page, Update Broker should not be enabled without generating the URL 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#127]
![image](https://user-images.githubusercontent.com/5267251/99702160-7a0f3500-2abb-11eb-96e5-b7ad35ffc614.png)

**Comment by theheapdump** [comment]
@kshitijbhardwaj  - pls take care

**Comment by bevanamit** [comment]
@Anmol: Is it possible to verify that the Client has put proper inputs for broker registration ?
@anmoldeep0123

**Comment by theheapdump** [comment]
@bevanamit @kshitijbhardwaj 
zerodha client will not be other then XA1346 -

2 alphabets + 4 alphanumeric 

secret and apikey - we have to trust the user 

generate URL is static content

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/99793707-0fa7d480-2b4f-11eb-96ad-13769d7e71c3.png)

zerdoha does not allow typing more than 6 in client ID

**Comment by theheapdump** [comment]
@bevanamit @kshitijbhardwaj

**Comment by bevanamit** [comment]
tested
