### ISSUE TITLE
User Story:13 Get AliceBlue broker account created

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#13]
Need alice blue trading account to integrate and test api's

**Comment by theheapdump** [comment]
please add labels, and add to project @bevanamit

**Comment by theheapdump** [comment]
@bevanamit 

use this doc here.

https://github.com/anmoldeep0123/kite-webapp/wiki/Alice-Blue-stock-broker---Everything-about-it-here

**Comment by bevanamit** [comment]
Account opening process stuck at IPV where we need to record video along with PAN card had couple of calls and screen sharing to understand the issue but no luck, in talks with the support team and also have dropped email to the team to look into the issue

**Comment by theheapdump** [comment]
cool. thanks for the update @bevanamit.  let's try to get alice blue as soon. as possible. Also can u find a fb/whatsapp / telegram group where there are alice blue users !!

**Comment by bevanamit** [comment]
Yes will work on that

**Comment by bevanamit** [comment]
IPV issue resolved, all things submitted from my end, waiting for authentication

**Comment by bevanamit** [comment]
Account opening procedure completed. Account will be activated in 24 hours, post that all details I will start making records.

**Comment by theheapdump** [comment]
awesome !! thanks @bevanamit

**Comment by bevanamit** [comment]
Will take care of those things sir no problem
