### ISSUE TITLE
QA - Test inactivity bases session expirty

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#132]
This is based on property 

pi.webgui.session.expiry=

it is not based on COOKIE expiry but an inactivity expiry. 

Create the SESSION COOKIE by logging in and do not perform the next action till the specified time. After that time session should expire.

We need to close this today 20/11

**Comment by theheapdump** [comment]
@bevanamit  - test this

**Comment by theheapdump** [comment]
can we close this

**Comment by theheapdump** [comment]
@bevanamit

**Comment by theheapdump** [comment]
@bevanamit  status ?

**Comment by bevanamit** [comment]
Sorry no update on this, have not worked
Regards
Amit A Bevinakatti

**Comment by bevanamit** [comment]
After last update on this have not worked again
Regards
Amit A Bevinakatti

**Comment by bevanamit** [comment]
This is tested...not much cases though
