### ISSUE TITLE
Bug: Issue with registration when we try to register second time

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#136]
Register a User
confirm otp and logout
Login using his credentials
update profile and logout
try registering another user now

Actual
Registration not happenning... here I was using the same browser tab after logging out
![image](https://user-images.githubusercontent.com/5267251/99884353-b8d7f300-2c53-11eb-9db7-3c48f0009ebc.png)

**Comment by theheapdump** [comment]
Fixed - this was a result of referral_code feature . It will be available in the next build.

**Comment by bevanamit** [comment]
tested ..havent observed this issue
