### ISSUE TITLE
Bug: user_profile does not get updated but user_state table gets updated with "PROFILE" when we try sending update profile after clearing local storage

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#137]
Register a new user with valid values
after confirmation of OTP logout the user
Now in same browser tab login with the user created above
it opens the Profile Page
fill in the required details Fname, lname etc
Open Inspect goto Application and localstorage
clear the local storage which has 

![image](https://user-images.githubusercontent.com/5267251/99884844-1c175480-2c57-11eb-933d-9c57442b431c.png)

once cleared it will be empty
Now click on Update on Profile Page
there is response from server 
{"redirectTo":null,"status":"SUCCESS","status_message":"Profile persisted succesfully","response":{"sts":"PROFILE"}}

User_state table is updated with PROFILE as state
but the user_profile table does not have user information

**Comment by theheapdump** [comment]
This is not an issue - i am not able to repro this with the steps .
Also profile update has nothing to do with local storage -
profile update is tied/linked to TBSESSIONID 

@bevanamit  - please re check this - i will be adding some logging today to the product .- you can retry this tomorrow.

**Comment by bevanamit** [comment]
Not reproducible
