### ISSUE TITLE
RELEASE READINESS | Fix LOGIN , REGISTER & RESET to use encryption decryption framework

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#139]

**Comment by bevanamit** [comment]
Ok

**Comment by bevanamit** [comment]
When we are sending data to backend the password is visible in clear text in the request header posted to the server

{ref: "123123123", phnNum: 1232342345, email: "bevanamit@gmail.com", passwd: "123123123",…}
cnfmPasswd: "123123123"
email: "bevanamit@gmail.com"
passwd: "123123123"
phnNum: 1232342345
ref: "123123123"

even in login screen we have it in plain
{username: "ambe@mailinator.com", password: "manage"}
password: "manage"
username: "ambe@mailinator.com"

**Comment by bevanamit** [comment]
api key and secret are encoded in request payload

![image](https://user-images.githubusercontent.com/5267251/99963036-29e3eb80-2db7-11eb-87f9-e5616aa48781.png)

**Comment by bevanamit** [comment]
reset password also sends password in plain text

{email: "ambe@mailinator.com", pass: "manage", c_pass: "manage"}
c_pass: "manage"
email: "ambe@mailinator.com"
pass: "manage"

**Comment by bevanamit** [comment]
These issues need to be fixed to pick for test

**Comment by theheapdump** [comment]
@kshitijbhardwaj  and @anmoldeep0123  to fix on a call

**Comment by theheapdump** [comment]
I think this is okay for now. Any application sniffing on our traffic will see encrypted data. We will fix this in next release if there is bandwidth and expertise on AES encryption decryption.

Closing this for now @bevanamit
