### ISSUE TITLE
User Story: 14 Create Name and Logo for the product

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#14]
Once product name is decided Name and Logo need to be created

**Comment by theheapdump** [comment]
please add appropriate labels for clarity, tracking, etc.

**Comment by theheapdump** [comment]
@bevanamit

**Comment by theheapdump** [comment]
@bevanamit - we need to also design a favicon based on the logo. It appears on the browser tab, a small icon.
@kshitijbhardwaj , from UI point of view , what are the dimension and file format required ?

**Comment by kshitijbhardwaj** [comment]
svg format is enough. Dimension anything is fine. Just shouldn't be too small.

​Regards,
Kshitij
9663774202

________________________________

**Comment by bevanamit** [comment]
Lets decide a name.... I have an idea for logo similar to this https://www.google.com/imgres?imgurl=http%3A%2F%2Fclipart-library.com%2Fimages%2F5iRKakXeT.jpg&imgrefurl=http%3A%2F%2Fclipart-library.com%2Fstock-market-images.html&tbnid=WhN-SiEBspS2zM&vet=12ahUKEwjZrNzZ2tzsAhWV2nMBHVuoDNoQMygoegUIARCDAg..i&docid=FZ4f35PTDmCW8M&w=1024&h=768&q=stock%20market%20images&hl=en-GB&ved=2ahUKEwjZrNzZ2tzsAhWV2nMBHVuoDNoQMygoegUIARCDAg

**Comment by bevanamit** [comment]
tradebull.com  UNAVAILABLE  - 7000 per year
tradehok.com UNAVAILABLE  - 7000 per year
tradebuddy.com UNAVAILABLE  - 7000 per year

tradebull.ai UNAVAILABLE  - 7000 per year
tradehok.ai UNAVAILABLE  - 7000 per year
tradebuddy.ai UNAVAILABLE  - 7000 per year

**Comment by bevanamit** [comment]
@anmoldeep0123 Not sure what  exactly you meant by previous comment

**Comment by theheapdump** [comment]
@bevanamit  - it's dummy data - please update in that format !!

**Comment by bevanamit** [comment]
Didn't get what dummy data??

**Comment by theheapdump** [comment]
Congratulations guys , we have finalized on tradebull product name, thanks to @kshitijbhardwaj. and others for this brainstorming.

Thanks, @bevanamit  for the logo preparation.

**Comment by theheapdump** [comment]
@bevanamit, let's finalize the logo size + favicon size as per other company standards and close this one.

**Comment by bevanamit** [comment]
Great work team... Will check what I can do on website front and any other
thing.... Also the company name we can have as TradeBull LLP if it's
available.

For this we need Anmol and Kshitij to have a Director Identification Number
created as well as a Digital Signature.

**Comment by theheapdump** [comment]
@bevanamit we need to fix favicon for web application

**Comment by theheapdump** [comment]
Let's close this @bevanamit  today

**Comment by bevanamit** [comment]
@kshitijbhardwaj favicon related files and instructions

[favicon_io.zip](https://github.com/anmoldeep0123/kite-webapp/files/5579785/favicon_io.zip)

Installation
First, use the download button to download the files listed below. Place the files in the root directory of your website.

android-chrome-192x192.png
android-chrome-512x512.png
apple-touch-icon.png
favicon-16x16.png
favicon-32x32.png
favicon.ico
site.webmanifest

Next, copy the following link tags and paste them into the head of your HTML.

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">

**Comment by bevanamit** [comment]
![tradebull3](https://user-images.githubusercontent.com/5267251/100494861-f369f000-316b-11eb-9a43-247190c9bb21.jpg)

Logo

**Comment by theheapdump** [comment]
what about favicon.ico

**Comment by bevanamit** [comment]
I have created and shared... These need to. Be included in Website

**Comment by bevanamit** [comment]
@kshitijbhardwaj favicon.zip attached, please check and update. Once done we can close this i believe.

**Comment by theheapdump** [comment]
Closing this as the logo is done.
