### ISSUE TITLE
Bug: Trying Mongo DB injection in login page does not give proper message

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#146]
Try giving the below for both username and password
admin' || '1' == '1'

![image](https://user-images.githubusercontent.com/5267251/100089146-3a5b9b00-2e77-11eb-85fd-54b5f4d964f7.png)

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/100533945-22499a00-3230-11eb-9a2d-4035b23da3f1.png)


I don't see an exception in my case . please check and let me know the exact scenario with logs.

@bevanamit

**Comment by bevanamit** [comment]
Not reproducible
