### ISSUE TITLE
User Story: 15 Add Spring Security | Authentication to Kite Web Platform Backend server

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#15]

**Comment by theheapdump** [comment]
I have added Spring Security + Basic Authentication + Session-Based Authentication code to our branch. Let's have a call tomorrow @bevanamit and see how we can test this ?

**Comment by kshitijbhardwaj** [comment]
great

**Comment by theheapdump** [comment]
This task has been completed.
