### ISSUE TITLE
User Story - 16 | Get API costs sorted for Kite Platform with (Zerodha - Bevan) for kiteandee customers

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#16]

**Comment by bevanamit** [comment]
dropped an email to id available at https://support.zerodha.com/category/trading-and-markets/kite-api/articles/what-are-the-charges-for-kite-apis

waiting for response

**Comment by bevanamit** [comment]
Response

The exchanges in India do not allow retail traders to fully-automate trades. There has to be manual UI interaction to place orders/ or the orders have to be placed manually.

----
I have asked for contact number to get in discussion.

**Comment by theheapdump** [comment]
I think this can be close now ?? @bevanamit

**Comment by bevanamit** [comment]
Actually yes.. Will do

**Comment by bevanamit** [comment]
Sorry forgot to do so.

**Comment by theheapdump** [comment]
@bevanamit - koi ni sir - mai kis baat ka scrum master hu fir - my job is to take care & remind :)
