### ISSUE TITLE
Bug: Clicking outside the Add New /Update Chartink Alert should not close the pop-up

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#164]
Closing the Pop up should be
1. Escape Key
2. Cross mark on right top to close the pop-up
3. Save
4. Cancel

![image](https://user-images.githubusercontent.com/5267251/101896672-537e7e80-3bcf-11eb-9508-5dd1bc0795aa.png)

**Comment by bevanamit** [comment]
not fixed for ESCAPE key @kshitijbhardwaj

**Comment by kshitijbhardwaj** [comment]
won't handle for escape.  Please don't blindly copy MFT.  This is the behaviour given by Material.

**Comment by bevanamit** [comment]
Haha... It's used to behavior sirji... I'm not blindly copying. We can
choose or not choose to do it.. I felt it's good coz I don't have to click
tab tab to go to cancel nor do I have to take mouse to cancel or cross
button.
