### ISSUE TITLE
Bug: Profit / Loss percentage should not be allowed to be configured for 0 "zero"

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#168]
![image](https://user-images.githubusercontent.com/5267251/101900008-c3433800-3bd4-11eb-9c83-e8ed7f907c05.png)

**Comment by theheapdump** [comment]
fixed in backend as well @bevanamit

**Comment by bevanamit** [comment]
@kshitijbhardwaj : not able to save the Profit and loss percentage with 0.05% ...we need to allow them to keep 0.05 and higher

**Comment by kshitijbhardwaj** [comment]
backend issue

**Comment by bevanamit** [comment]
tested
