### ISSUE TITLE
User Story - 17 | Create a business plan (PPT) for kite platform (kiteandee).

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#17]
Let us create an earning business model + profit model with real time data for 5 customers.

It should have the earnings for kiteandee per customer per day & per trading month (22 days).

E.g. if a customer does trading and earns a net profit of 20,000 INR , what would be the kiteandee profit share from 20,000 
how are we calculating that

-e.g.
1). 1%  of  the net profit 
2). fixed day charges whether profit or loss e.g. 100 rupees per day 
3). fixed charges (50 bucks per day) + 1% of the net profit.

Think about it, all the possibilities or anything out of the box of (1,2,3) 

We need to have this by November. 15

**Comment by bevanamit** [comment]
Added 3 page slide to define the Business Models that can be planned, shared at

https://drive.google.com/file/d/13cSem21Enhm3HHFwfAL1A5PE4INa_Uln/view?usp=sharing

**Comment by bevanamit** [comment]
Added business plan return estimates excel sheet

https://drive.google.com/file/d/1u1iBeJ_dVYHByl7LYtXbMsWlL3V7m91r/view?usp=sharing

**Comment by bevanamit** [comment]
@anmoldeep0123 @kshitijbhardwaj  please review and provide your inputs if any.

**Comment by theheapdump** [comment]
in the "invest with us" model, we need to at least provide FD rates. every month 3.5 - 4. %, less than that is. a loss. for any customer.

**Comment by theheapdump** [comment]
@bevanamit, this is. a doc task, please add this info (drive loc and excel) in. a wiki. the issue will be closed and data will be lost.
If a task is a doc task, let's create a wiki for them

**Comment by bevanamit** [comment]
Ok fine will do that... The customer interest model is higher than bank...
1 month will give 1.5% and so on and so forth

**Comment by theheapdump** [comment]
@bevanamit  move this data to wiki and close this task. Thanks

**Comment by bevanamit** [comment]
Added at https://github.com/anmoldeep0123/kite-webapp/wiki/Business--related-Information
