### ISSUE TITLE
Bug: Duplicate Alerts should not be allowed

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#174]
![image](https://user-images.githubusercontent.com/5267251/101907862-28048f80-3be1-11eb-8efb-a66e91cb489b.png)

**Comment by kshitijbhardwaj** [comment]
@anmoldeep0123  Can u add one validation for this in backend.

**Comment by theheapdump** [comment]
Fixed

**Comment by bevanamit** [comment]
tested
