### ISSUE TITLE
Bug: Exception faced when tried to save with the same data as in image attached

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#175]
![image](https://user-images.githubusercontent.com/5267251/101908744-8a11c480-3be2-11eb-964d-dc4abab3bb9c.png)

Logs
[tradebull.log](https://github.com/anmoldeep0123/kite-webapp/files/5679349/tradebull.log)

**Comment by theheapdump** [comment]
This is due to allowing duplicate alert for the same customer . This will be fixed after we do not allowe duplicate alert names for same customer

**Comment by bevanamit** [comment]
tested
