### ISSUE TITLE
Bug: Add Button in Chartink does not give any idea to the User why it is disabled

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#176]
After adding 11 entries for Alerts in Chartink list, the ADD button gets disabled, but there is no way for user to know what went wrong.

Maybe we can have a label stating the maximum alerts allowed are 10 and also correct that as I was able to add 11 entries.

![image](https://user-images.githubusercontent.com/5267251/101927039-08c62c00-3bfa-11eb-8db1-a7f1eb0d61cd.png)

**Comment by bevanamit** [comment]
@anmoldeep0123 @kshitijbhardwaj , currently when the ADD button is disabled after 10 Alerts, the Add button gets disabled, but the User has no Idea why... 

Lets show Mouse Hover Message on Add button which says the Maximum Alerts allowed is 10

Or one other thing is we can  Allow adding more but only allow enabling 10.

Lets take a call on this

**Comment by kshitijbhardwaj** [comment]
i tried adding mouse hover don't know y it didn't work. Will fix it

**Comment by bevanamit** [comment]
Ok sure

**Comment by bevanamit** [comment]
![image](https://user-images.githubusercontent.com/5267251/102366116-43efa300-3fde-11eb-86f6-9f2ba0145196.png)
tested
