### ISSUE TITLE
Shifting from any screen to Chartink it is taking around 1.4seconds

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#177]
Shifting from any screen to Chartink it is taking around 1.4seconds

**Comment by theheapdump** [comment]
are there any backend calls involved ?? GET is involved i see

**Comment by bevanamit** [comment]
Logs at least i see

2020-12-11 16:32:17 info  o.k.s.TradeBullSessionIDAuthnFilter [https-jsse-nio-8080-exec-7]
                                        ANMOL = /tb/ui/v1/actions/cinkalert
2020-12-11 16:32:17 debug o.s.d.m.c.MongoTemplate [https-jsse-nio-8080-exec-7]
                                        find using query: { "session_id" : "7DE9A8D4C337CEAB3E9B46D10A68A31558EF2338441FA404921F1AE2E92DCE27"} fields: {} for class: class org.kiteandee.dao.UserSession in collection: user_session
2020-12-11 16:32:17 debug o.s.d.m.c.MongoTemplate [https-jsse-nio-8080-exec-7]
                                        find using query: { "session_id" : "7DE9A8D4C337CEAB3E9B46D10A68A31558EF2338441FA404921F1AE2E92DCE27"} fields: {} for class: class org.kiteandee.dao.UserSession in collection: user_session
2020-12-11 16:32:17 debug o.s.d.m.c.MongoTemplate [https-jsse-nio-8080-exec-7]
                                        Saving Document containing fields: [_id, session_id, user, is_active, source_ip, user_agent, expiry_time, max_age, createdBy, lastModifiedBy, createdDate, lastModifiedDate, _class]
2020-12-11 16:32:17 debug o.s.d.m.c.MongoTemplate [https-jsse-nio-8080-exec-7]
                                        find using query: { "email_address" : "ambe121@mailinator.com"} fields: {} for class: class org.kiteandee.dao.User in collection: user
2020-12-11 16:32:17 debug o.s.d.m.c.MongoTemplate [https-jsse-nio-8080-exec-7]
                                        find using query: { "session_id" : "7DE9A8D4C337CEAB3E9B46D10A68A31558EF2338441FA404921F1AE2E92DCE27"} fields: {} for class: class org.kiteandee.dao.UserSession in collection: user_session
2020-12-11 16:32:17 debug o.s.d.m.c.MongoTemplate [https-jsse-nio-8080-exec-7]
                                        find using query: { "customer_id" : "TBPCambe09877TRA"} fields: {} for class: class org.kiteandee.dao.ChartInkAlertConfig in collection: chartink_alert_cfg

**Comment by bevanamit** [comment]
I think the data should be cached, we cannot pull everytime for the same user session.

**Comment by theheapdump** [comment]
Cannot cache in this release.  @bevanamit  closing this
