### ISSUE TITLE
Bug: Editing an existing alert gives OK message

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#183]
![image](https://user-images.githubusercontent.com/5267251/101935501-31075800-3c05-11eb-9211-4d95c3357c49.png)
[tradebull.log](https://github.com/anmoldeep0123/kite-webapp/files/5680673/tradebull.log)

**Comment by theheapdump** [comment]
@bevanamit  - fixed in latest build

**Comment by bevanamit** [comment]
Ok

**Comment by bevanamit** [comment]
testd
