### ISSUE TITLE
Bug: Saving Alert gives OK message

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#188]
![image](https://user-images.githubusercontent.com/5267251/101986656-21dfe300-3cb5-11eb-8af7-93a4e70abf12.png)

[tradebull.log](https://github.com/anmoldeep0123/kite-webapp/files/5683240/tradebull.log)

**Comment by kshitijbhardwaj** [comment]
backend issue

**Comment by bevanamit** [comment]
@anmol please take care of this

**Comment by theheapdump** [comment]
@bevanamit - please retest

**Comment by bevanamit** [comment]
tested
