### ISSUE TITLE
Bug: Clicking on Signupshould show the Pricing Page in one go

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#195]
The clicking on Sign-up scrolls the page to half the pricing part...attached screenshot, please show full plans along with sign-up buttons...currently the page scrolls till here

![image](https://user-images.githubusercontent.com/5267251/102173021-1ca2b400-3ec0-11eb-9eb7-b450ca447c9f.png)

**Comment by bevanamit** [comment]
@kshitijbhardwaj the sign-up buttons on the cards are still not visible. the Cards should be shown completely

**Comment by bevanamit** [comment]
Fix the issue in Firefox also , IE we can choose not to support

**Comment by kshitijbhardwaj** [comment]
its already fixed in firefox. and its happening perfectly in my system. Can u check again. I have done whatever i can do from my end

**Comment by bevanamit** [comment]
Observed that the zoom of Chrome and Firefox when 90% works as expected, but not when its normal which is 100%
@kshitijbhardwaj @anmoldeep0123

**Comment by kshitijbhardwaj** [comment]
i can't do anything for that. I can fix it at one place. It depends upon the place where the Url starts  it will always go there and if the whole body is long that it doesn't satisfy any zoom levels  we can't  do much.
