### ISSUE TITLE
Bug: Unknow error observed in UI

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#201]
Attached logs and screenshot

![image](https://user-images.githubusercontent.com/5267251/102371392-27566980-3fe4-11eb-845b-f0386dbeba5c.png)
[tradebull.log](https://github.com/anmoldeep0123/kite-webapp/files/5703787/tradebull.log)

**Comment by kshitijbhardwaj** [comment]
backend is down thats why sir mere ko bhi dikha raha hai

**Comment by theheapdump** [comment]
this is a backend down issue . but still UI should show something meaningful thatn unknown error.

**Comment by theheapdump** [comment]
@kshitijbhardwaj

**Comment by bevanamit** [comment]
Not faced
