### ISSUE TITLE
RELEASE |  Free Tier | Do not allow to create more than 2 (1 BUY / 1 SELL) alerts.

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#202]
UI - Task  Front End Restrictions 

Backend - Validations Restrictions 

@bevanamit @kshitijbhardwaj @anmoldeep0123

**Comment by theheapdump** [comment]
@bevanamit  close this as duplicate if shiri already handling this

**Comment by bevanamit** [comment]
Have a duplicate task in web-ui repo
