### ISSUE TITLE
Bug: When i know the TB login link and try to open it directly i get 404 error

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#207]
Try opening https://tradebullz.in:61987/login
![image](https://user-images.githubusercontent.com/5267251/102386296-e9ae0c80-3ff4-11eb-94b8-5ea2d3acc4ae.png)

**Comment by bevanamit** [comment]
Also try opening Link in new tab by using right click on the navigation panel and clicking on Open link in new tab

**Comment by theheapdump** [comment]
@kshitijbhardwaj to comment

**Comment by bevanamit** [comment]
https://tradebullz.in:61987/login doesnt work as expected

**Comment by kshitijbhardwaj** [comment]
please test with proper url. i said # should be there in urls.  Url which u r trying is invalid

**Comment by bevanamit** [comment]
Are sirji... Jab raise kiya tabhi bhi wahi diya tha maine... Thik hai
dekhta hun

**Comment by bevanamit** [comment]
its\ now works with /#/login
