### ISSUE TITLE
Bug: Message  for Profile update should be changed - use backend message

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#209]
![image](https://user-images.githubusercontent.com/5267251/102387012-dfd8d900-3ff5-11eb-90e0-87927c76a868.png)

It should be "Profile updated successfully"

**Comment by theheapdump** [comment]
Backend is sending correctly

{
	"redirectTo": null,
	"status": "SUCCESS",
	"status_message": "Profile updated successfully",
	"response": null
}

but UI is showing its own message

@kshitijbhardwaj

**Comment by bevanamit** [comment]
tested
