### ISSUE TITLE
Bug: Date issue not fixed in firefox for YEAR we can type in 5 digits

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#213]
![image](https://user-images.githubusercontent.com/5267251/102390333-4b24aa00-3ffa-11eb-8f72-d14ff747d244.png)

**Comment by kshitijbhardwaj** [comment]
i have added validation for dates in firefox. Now user can't enter year in 5 digits. This should fix the issue.

**Comment by bevanamit** [comment]
Still able to type 5 digits ...but error is shown so fixed
