### ISSUE TITLE
Bug: Using firefox date saved and shown issue

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#214]
Register
Login
Enter Profile details and Enter invalid Date, which is 5 digits in year in this case
The Value stored in DB is "0"
Navigate to Profile settings from left Navigation Panel
The DATE should be shown not configured

But it is shown 1/1/1970

![image](https://user-images.githubusercontent.com/5267251/102391048-35fc4b00-3ffb-11eb-8e77-300b288658ba.png)

**Comment by theheapdump** [comment]
@kshitijbhardwaj  issue

**Comment by kshitijbhardwaj** [comment]
i have added validation for dates in  firefox. Now user can't enter year in 5 digits. This should fix the issue.
