### ISSUE TITLE
Bug: The User option in Right top appear merged with Profile Information page

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#216]
There should be some bordering or color difference for the User Options

![image](https://user-images.githubusercontent.com/5267251/102393935-04857e80-3fff-11eb-872f-a40e1ff50671.png)

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/102400416-e708e280-4007-11eb-9cd1-341cde8f7f72.png)


In google chrome it seems fine

**Comment by theheapdump** [comment]
@bevanamit - why we are. showing email id as ...... earlier it used. to be name and it was fine . @kshitijbhardwaj 
why changed ?

**Comment by bevanamit** [comment]
I had raised issue not to show Anmol... Now before the user actually fills
his profile details he should be either shown this or we show only when the
user enters his details till then not show anything and only 2 options till
then.

**Comment by kshitijbhardwaj** [comment]
Regarding the merge i have changed the color of one of them. to separate it out

**Comment by kshitijbhardwaj** [comment]
Email i am showing because thats the one thing we will always have because we register on that basis only. Its something we never allow them to change.  So no confusion of hiding or showing. 
Also i don't see any issue in showing email.

**Comment by kshitijbhardwaj** [comment]
OK i can show name. But backend need to send name in login response. Until and unless name is configured we will keep showing mail id. once he configures name we can show name then.
Requires back end change.

**Comment by theheapdump** [comment]
@bevanamit , please check if duplicate n close .

**Comment by bevanamit** [comment]
Taken care
