### ISSUE TITLE
Build : Write a build script (.sh & .bat) for support UI build for kite-webapp 

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#24]
Since this will eventually run on Jenkins - all cases need to be handled.
e.g. node not available 
node version wrong 

etc etc.

**Comment by bevanamit** [comment]
ok...i would need details on what needs to be done...i mean what calls to be made to build and once built i will push it to git only so that it is versioned as well

**Comment by bevanamit** [comment]
Need steps that need to be taken care for this task.

**Comment by theheapdump** [comment]
@kshitijbhardwaj

**Comment by bevanamit** [comment]
Guys needs steps for this

**Comment by theheapdump** [comment]
@kshitijbhardwaj  , please help @bevanamit  here .

**Comment by bevanamit** [comment]
Guys give a flow here so that  i can take a look on how to do it.

**Comment by theheapdump** [comment]
Done
