### ISSUE TITLE
User Story 21 - MongoDB installation & integration with Spring Boot back end server for Kite Platform

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#28]
To integrate the backend server with mongodb

**Comment by bevanamit** [comment]
https://docs.mongodb.com/manual/tutorial/configure-ssl-clients/#mongo-shell-configuration-using-tls-options

https://stackoverflow.com/questions/28106940/mongodb-and-nodejs-ssl-secure-connection/33926129

**Comment by theheapdump** [comment]
MongoDB integration complete - NON SSL for now .
