### ISSUE TITLE
User Story 22 : Profile Page UI Development -  Linked to User Story - 1

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#32]
Requirements:

@kshitijbhardwaj , me, and Amit and agreed upon the UI flow. e.g. LinkedIn customer onboarding is a good example. You can as well. try that with a dummy email. (needs email confirmation).

Advantages - It is UI driven than. user-driven. Please do a quick register on LinkedIn to understand the onboarding.

backend will maintain a STATE machine for each onboarding. States are. ( PROFILE &  BROKER )

1. After Registration completes, the User is to be presented with a card - for Profile details 

Fields in this form

First Name, Last Name

Small Photo Upload / Avatar -  OPTIONAL

NickName

Gender

Birth Date - OPTIONAL

Save / Continue. - send the async call to the backend to. update STATE. to. profile and save profile data

2.  Next present a broker selection card -> select broker drown down ->  ZERODHA / ALICE BLUE / etc 

3. In the same card or a new card. (up to UI developer) show the zerodha form fields 

TEXTBOX - Enter ZERODHA CLIENT ID

TEXTBOX - Enter API KEY

TEXTBOX - Enter API SECRET

BUTTON - Generate Kite Connect URLs - ASYNC CALL -backend

TEXTBOX - Non editable - Redirect URL:

TEXTBOX - Non editable - Postback URL:

4. In the above state, there are 3 flows

FLOW 1 - MAY. BE LATER - state remains PROFILE - no async call - redirect to DASHBOARD - blank screen 
a RED UI. text somewhere on the. top - Broker Information Missing. -> Clickable.  -> ROUTE. to. be. decided later 

FLOW 2 - DON'T HAVE AN ACCOUNT ? - CREATE ONE. -> First play a official kite developer account creation video and provide a link (FOCUS) for redirect to Kite Developer. -> Video-assisted Kite developer account creation -> user comes back fills the details -> save -> ASYNC call to backend (update state to BROKER) -> Route to dashboard -> Next to be decided later

FLOW 3-> Have the APP details , fill and save -> then same as FLOW 2 -> ASYNC call to backend -> update STATE to BROKER  -> Dashboard.

**Comment by theheapdump** [comment]
![WhatsApp Image 2020-10-30 at 00 03 31](https://user-images.githubusercontent.com/7692754/97662761-edfe8480-1a9d-11eb-8f49-b9a1bd7b5000.jpeg)
![WhatsApp Image 2020-10-30 at 00 04 37](https://user-images.githubusercontent.com/7692754/97662774-f1920b80-1a9d-11eb-9bd6-e28d2f37c645.jpeg)
![WhatsApp Image 2020-10-30 at 00 05 31](https://user-images.githubusercontent.com/7692754/97662778-f22aa200-1a9d-11eb-898c-7f1dc55aeb0b.jpeg)

**Comment by theheapdump** [comment]
![WhatsApp Image 2020-10-30 at 00 06 13](https://user-images.githubusercontent.com/7692754/97662855-20a87d00-1a9e-11eb-9897-9120cb4ef610.jpeg)
![WhatsApp Image 2020-10-30 at 00 07 48](https://user-images.githubusercontent.com/7692754/97662862-243c0400-1a9e-11eb-9589-dac836f58428.jpeg)
![WhatsApp Image 2020-10-30 at 00 08 46](https://user-images.githubusercontent.com/7692754/97662864-256d3100-1a9e-11eb-9c42-017a2cda2f38.jpeg)
![WhatsApp Image 2020-10-30 at 00 09 22](https://user-images.githubusercontent.com/7692754/97662866-2605c780-1a9e-11eb-99ec-8d8db56abf22.jpeg)

**Comment by bevanamit** [comment]
@kshitijbhardwaj @anmoldeep0123 : please comment if there are changes to the screen as per you guys decided.

**Comment by theheapdump** [comment]
my thought was @bevanamit , it should be quite similar to LinkedIn as much as possible .

**Comment by bevanamit** [comment]
Then we take the names in 2 parts first and second name... Let's remove the
nickname as I don't see we are using it anywhere.

**Comment by theheapdump** [comment]
name could be long - just in case , we will use nickname for communications -on UI and backed - Informal
