### ISSUE TITLE
User Story 23 - Videos For KiteAndee Platform 

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#33]
Expected from this story is :

1. Marketing video to be sent to customers to buy the product. (We can pay to get. this done). [After UI is complete / since video needs UI snapshots ]
2. Within App Video to assist account creation on https://developers.kite.trade/apps [ November 30th ]

**Comment by bevanamit** [comment]
@anmoldeep0123 @kshitijbhardwaj I will take care of creating product training and broker configuration videos once we have UI ready... No need to outsource will take care

**Comment by bevanamit** [comment]
Step by Step guide created for Customer to Register TradeBull and Zerodha https://drive.google.com/file/d/1CA6uzrjV_RJL7GBsYp0VEOVmubCMzLOT/view?usp=sharing
