### ISSUE TITLE
Bug: Issues with Login Page/Confirm Email

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#40]
1. For Lets Confirm Your Email, we just need to say type in the six digit code we sent. The generate otp button should be removed.

2. On Hover Hand should appear for "Send Again" for Didn't receive the code?

**Comment by kshitijbhardwaj** [comment]
Fixed the issue. Except the removing the generate Otp btn that will fix when we get Login page backend.

**Comment by theheapdump** [comment]
@bevanamit , please verify this

**Comment by bevanamit** [comment]
Ok.. Same link right

**Comment by bevanamit** [comment]
Is the build updated... I see the behavior is same

**Comment by bevanamit** [comment]
The error/warning is shown only when the Register button is clicked, this has to be on key press

**Comment by kshitijbhardwaj** [comment]
For point 1 we are removing the Generate Otp button. On login we will check if sts is registered, auto email will be sent to user's email id. Rest all send again logi remains same.
Assigning to anmol for adding logic in backend.

**Comment by theheapdump** [comment]
@bevanamit - will see once login is finished

**Comment by theheapdump** [comment]
@bevanamit , please test this .
