### ISSUE TITLE
Bug: Profile settings Page issues

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#41]
As Per https://github.com/anmoldeep0123/kite-webapp/issues/32

1. There should be First Name, Last Name both, but there is 'Full Name' in UI
2. Gender should be Selection Male/Female
3. Date of Birth, we do not Need time here 
4. Only DOB should be made option and "Skip" button should be enabled only when all mandatory data is filled

**Comment by kshitijbhardwaj** [comment]
Fixed

**Comment by bevanamit** [comment]
Text in first name textbox should be updated to Enter your first name, the same applies to last name

**Comment by kshitijbhardwaj** [comment]
Fixed

**Comment by theheapdump** [comment]
based on @kshitijbhardwaj  last comment - fixed . @bevanamit  please re-test
