### ISSUE TITLE
Bug: Naming conventions for fields used in screens

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#42]
Let us decide and use a particular naming convention for UI fields, as I have encountered "phnnum" for phone number and "ref" for referral code.

@anmoldeep0123 @kshitijbhardwaj , lets decide on fields naming convention and follow the same so that we will be able to easily locate/name any new field without much difficulty.

**Comment by theheapdump** [comment]
on UI , names should be clear - req / res body names do not matter - i have deliberately kept them short / non understandable  so that if anyone look at network tab , they do not understand what's happening .

@bevanamit  revisit this & if on UI if names are incorrect -> mention them here.

**Comment by bevanamit** [comment]
As per last comment makes sense if we want to avoid user identifying things
in network tab. Will close this.
