### ISSUE TITLE
RELEASE READINESS : DB table for Clients/Customers to check the current status Active/Inactive and the payment information

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#45]
DB table for Clients/Customers to check the current status Active/Inactive and the payment information

**Comment by bevanamit** [comment]
We should be able to identify if a user is on trial, or paid and is currently account is active or not.

**Comment by theheapdump** [comment]
@bevanamit  pls move this to the open project where shiri has access. 
Also will it be taken care of by some existing before-july tasks

**Comment by bevanamit** [comment]
The pricing page finalization will take care of this, no need to move will
close it
