### ISSUE TITLE
User Story 27 : Implement Session Expiry and Session Validation For TradeBull Backend

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#48]

**Comment by theheapdump** [comment]
Session Expiry and validation backend done. @bevanamit  , please test this , it's very important

**Comment by theheapdump** [comment]
@bevanamit create a QA story for this , if already nit there.

**Comment by bevanamit** [comment]
Would need some inputs to understand on what needs to be done

**Comment by theheapdump** [comment]
@bevanamit - we will have a demo tomorrow on this

**Comment by bevanamit** [comment]
Ok sir.. Thank you
