### ISSUE TITLE
User Story 27 : Implement Session Expiry and Session Validation Error Handling For TradeBull UI 

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#49]

**Comment by theheapdump** [comment]
@kshitijbhardwaj , i have finished this on back end , please think abt front end . 

e.g remove cookie in browser and send a call

**Comment by kshitijbhardwaj** [comment]
@anmoldeep0123  This is done in UI side

**Comment by theheapdump** [comment]
Re-opening this to be implemented as we discussed this today. 

@bevanamit  This is basis for your QA testing. 

@kshitijbhardwaj  please deliver this today to @bevanamit  for testing.

**Comment by kshitijbhardwaj** [comment]
Done. PLease test

**Comment by theheapdump** [comment]
we can close this - @bevanamit  make sure this is fixed for logout also - basically any page / any backend call - session expiry should have same behavior.

**Comment by theheapdump** [comment]
closing this user story

**Comment by theheapdump** [comment]
Thank you @kshitijbhardwaj
