### ISSUE TITLE
User Story - 5 : Create Sign Up / Register Now QA 

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#5]

**Comment by bevanamit** [comment]
Does this require anything from me ??

**Comment by theheapdump** [comment]
@bevanamit, once UI is available , we can start thinking on 
1. selenium automation for UI 
2 rest-assured test cases for register REST API

**Comment by theheapdump** [comment]
@bevanamit  u can start working on this now .

**Comment by theheapdump** [comment]
Use https://35.187.245.85:8080/ as a sample environment.

**Comment by theheapdump** [comment]
@bevanamit  u can start testing this from tomorrow

**Comment by bevanamit** [comment]
Great

**Comment by theheapdump** [comment]
@bevanamit , we need to close this before Friday

**Comment by bevanamit** [comment]
It's available today... Will complete by eod

**Comment by bevanamit** [comment]
will complete today

**Comment by bevanamit** [comment]
Completed testing...automation in progress

**Comment by theheapdump** [comment]
finally
