### ISSUE TITLE
Bug: UI look completly changed after trying to login with proper email

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#52]
give proper inputs for Login 
click Login
after it shows OK the screen did not change
Then clicking on Login a couple of times the Login UI and Register UI changes to attached drive
https://drive.google.com/drive/folders/14cPx6ONp1SXcMsv1o-CIkBhm8N72anRE?usp=sharing

**Comment by kshitijbhardwaj** [comment]
Not able to reproduce this. Can u ple provide the steps

**Comment by bevanamit** [comment]
The details are shared at
https://drive.google.com/folderview?id=14cPx6ONp1SXcMsv1o-CIkBhm8N72anRE

**Comment by theheapdump** [comment]
@kshitijbhardwaj  - please have a look @ this - if not an issue - change label to fixed and reassign to @bevanamit

**Comment by theheapdump** [comment]
@bevanamit
