### ISSUE TITLE
Bug: Multiple Registration with the same email and phone number should not be allowed

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#53]
Try registering with same email and phone more than once, it should not allow and should give proper message stating the phone number / email is already registered

**Comment by kshitijbhardwaj** [comment]
Backend need to handle this. Assigning to anmol

**Comment by theheapdump** [comment]
yes - known issue - will fix it

**Comment by theheapdump** [comment]
Fixed - please have a look @bevanamit

**Comment by bevanamit** [comment]
Not fixed yet

**Comment by theheapdump** [comment]
it's fixed sir  not possible

**Comment by theheapdump** [comment]
weird

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/99666503-1708a880-2a91-11eb-9666-216b47fc282b.png)

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/99666582-2c7dd280-2a91-11eb-8b81-02e2e7bc6f59.png)

**Comment by bevanamit** [comment]
![Uploading image.png…]()
