### ISSUE TITLE
Bug: Remove Full and and Add First Name and Last name to Profile Screen as this is standard for most UI

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#54]
Currently we are giving only Full Name, please change it to "First Name" and "Last Name" to keep the profile information standard with other UI's specially social websites

**Comment by theheapdump** [comment]
@kshitijbhardwaj  @bevanamit  - that's right but now that i think of, will it matter - separate or same. ?? 
thoughts ??

**Comment by bevanamit** [comment]
Let's have it separate... In care we have to use it later at least we have
that information

**Comment by kshitijbhardwaj** [comment]
DOne

**Comment by theheapdump** [comment]
@kshitijbhardwaj  , for better tracking -> close issue and mark it as done in projects. thanks

**Comment by theheapdump** [comment]
@kshitijbhardwaj  , what is the updated request body ??
