### ISSUE TITLE
Bug: Date of Birth for Profile should be checked for Validation

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#56]
Date of Birth for Profile should be checked for Validation for below
1. It should not be future
2. If possible check if its at least 6yr old

**Comment by theheapdump** [comment]
yes. - should be ateast 16 years of age ??? @bevanamit

**Comment by bevanamit** [comment]
10 years is good enough

**Comment by theheapdump** [comment]
this is a simple issue and we can get rid of it quickly @kshitijbhardwaj

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/100453557-24e9a980-30e1-11eb-801b-56749ea11688.png)

**Comment by theheapdump** [comment]
Bug: Date in profile settings is allowing 6 digits #115

**Comment by bevanamit** [comment]
This is not fixed
![image](https://user-images.githubusercontent.com/5267251/100537711-bfb4c600-3250-11eb-8d64-ccfa28a70dbb.png)

**Comment by kshitijbhardwaj** [comment]
Not able to repro this issue for which u have reopened. Can u please provide the steps to reproduce

**Comment by bevanamit** [comment]
Sorry, forgot to mention browser... its seen in Firefox

![Uploading image.png…]()

**Comment by bevanamit** [comment]
@kshitijbhardwaj is this taken care for firefox ?

**Comment by kshitijbhardwaj** [comment]
fixed
