### ISSUE TITLE
Bug: OK box shown when Update Profile is Clicked needs to be different

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#58]
The ok box shown is not good. this has to be changed, maybe we can do something like MFT provide successful notification for 3 to 5 seconds or some other better way. https://drive.google.com/file/d/1Pfe4e8Iy5RNV5HFUT8-pzVTdDW2Kek7_/view?usp=sharing

**Comment by theheapdump** [comment]
i don't think it's a bug

**Comment by theheapdump** [comment]
@bevanamit

**Comment by bevanamit** [comment]
Not observed
