### ISSUE TITLE
Bug: Select Broker drop down not showing the selected Broker

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#59]
Select Broker drop down not showing the selected Broker

@kshitijbhardwaj @anmoldeep0123 : should we show this as Radio button, we may include more in future but the Drop down provided not looking right, either its not looking good as its smaller or some other issue with look.

**Comment by kshitijbhardwaj** [comment]
Fixed the issue and drop down now showing in full length of screen

**Comment by bevanamit** [comment]
tested

**Comment by theheapdump** [comment]
i  don't think radio button is a good option
