### ISSUE TITLE
User Story - 6 : Create Log In screen  - QA

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#6]

**Comment by bevanamit** [comment]
The Login screens will be designed to support multiple brokers:

The login links will be like
https://<ourdomain>.com/<brokername_alias>/login

The login screen will have inputs:
username/email
Password
OTP (mobile OR email)

**Comment by theheapdump** [comment]
Few corrections here 

1. login is independent of the broker name. broker name need not come in the URL. 
However, broker specific config changes would have <brokername> as path_param or query_param.
2. For now: the customer can select a default broker that will always be used when he logs in.
3. Customer can modify the default broker OR select another broker before trading for the day.
4. The context of the Configurations will be saved with the broker context. - TBD later.

**Comment by theheapdump** [comment]
@bevanamit , when we have some amount of UI from @kshitijbhardwaj,  we can start thinking on QA test cases for log-in
that will include session management. 

session - token linking for multiple tenants 
session lifetime 
session expiry 
session cookie based tests 
multiple sessions for the same customer 

start thinking on those lines for this QA user story

**Comment by bevanamit** [comment]
Will research on this

**Comment by theheapdump** [comment]
@bevanamit , u can start selenium on this from tomorrow

**Comment by theheapdump** [comment]
@bevanamit , we need to close this before Friday

**Comment by bevanamit** [comment]
Will complete by EOD

**Comment by bevanamit** [comment]
Screen done, automation in progress for the same
