### ISSUE TITLE
RELEASE READY | Make the user force / open / click read T & C via. PDF | HTML | Google Drive before he clicks Register Me

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#61]
Information "I" beside Generate URL's button on Register Screen needs to be documented properly

or a Video to show how registration is done has to be created and shown in a frame  just like we see in FB

**Comment by theheapdump** [comment]
@bevanamit  is it still an issue

**Comment by bevanamit** [comment]
We can use this "i" to point to https://drive.google.com/file/d/1CA6uzrjV_RJL7GBsYp0VEOVmubCMzLOT/view?usp=sharing

**Comment by theheapdump** [comment]
@bevanamit  closing this as duplicate as already handled in one of the before-july tasks
