### ISSUE TITLE
Bug: Change the WebPage Title and Icon for TradeBull

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#63]
WebPage title
Login Page "New to TradeGenie?" to"New to TradeBull?"
Register page as well

**Comment by kshitijbhardwaj** [comment]
Done

**Comment by kshitijbhardwaj** [comment]
Done

**Comment by bevanamit** [comment]
@kshitijbhardwaj Icon needs to be changed

**Comment by theheapdump** [comment]
@bevanamit  please us the icon , logo ticket to create a favicon. closing this .
