### ISSUE TITLE
Bug: Do not allow typing characters and more than 10 numbers for Phone number in Register Page

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#64]
Do not allow more than 12 numbers for Phone number in Register Page

**Comment by bevanamit** [comment]
Keep the numbers fixed to 10.... and by default add (+91) for now to the number, basically for India

**Comment by theheapdump** [comment]
+91 [ ------------------]

**Comment by kshitijbhardwaj** [comment]
Added validation for mobile no to accept +91 or 0 in begining with 10 digit number to follow.

**Comment by bevanamit** [comment]
@kshitijbhardwaj not resolved.. We should allow only 10digits

**Comment by theheapdump** [comment]
@kshitijbhardwaj yes even.i noticed this - more than 10 should not be allowed to be even typed

**Comment by kshitijbhardwaj** [comment]
Guys what is the issue in typing. We are showing error message on wrong entry. SO its getting typed or not doesn't matter.

**Comment by theheapdump** [comment]
it's good to have - max length !!! 
otherwise, also it's ok 

i leave it to @bevanamit  to decide.

**Comment by bevanamit** [comment]
Fix it with Max length.. If required in future we can choose to increase
length

**Comment by bevanamit** [comment]
@kshitijbhardwaj please take care of this

**Comment by kshitijbhardwaj** [comment]
In my opinion its fine. I need to see how to achieve that some regex and all, which i don't want to do considering the severity and need of the issue. I have seen millions of ebsite like this. Requesting you to please close this. for now if customer cmes we will see.

**Comment by bevanamit** [comment]
Sirji... We are not MFT... We will not have customers coming to us saying
this is issue.... It is how we want to present ourselves to people.

**Comment by theheapdump** [comment]
@kshitijbhardwaj  , yar maxlen validation to dalna hai .... one line of code . kar hi do , kya dikkat hai

**Comment by bevanamit** [comment]
@kshitijbhardwaj , please allow only numbers, you are still allowing any other character other than number

Do not allow typing characters and more than 10 numbers for Phone number in Register Page

1 part is solved max length is 10 now

**Comment by kshitijbhardwaj** [comment]
As discussed above max length validation added. Now why again do not allow characted request?

**Comment by bevanamit** [comment]
Sir I had already mentioned in issue description... I hope we are having
validation related tasks separate... This is actually applicable for OTP
also... But it's not of priority as of now

**Comment by bevanamit** [comment]
![Uploading image.png…]()

**Comment by bevanamit** [comment]
Broken in chrome for number of digits
![image](https://user-images.githubusercontent.com/5267251/99878609-c4fc8a00-2c2c-11eb-91be-54878fb2bc41.png)

**Comment by bevanamit** [comment]
@kshitijbhardwaj @anmoldeep0123 as we decided to move further from register , login , OTP and reset..closing this for now
