### ISSUE TITLE
Bug: If Email/Phone number or password is not correct then we should show proper message in Login Screen

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#65]
Bug: If Email/Phone number or password is not correct then we should show proper message in Login Screen, currently we are showing "OK"

**Comment by kshitijbhardwaj** [comment]
Validation needs to happen in backend and proper message need to be thrown from backend. Hence assigning to anmol

**Comment by kshitijbhardwaj** [comment]
THis is fixed

**Comment by bevanamit** [comment]
The message is currently
The email address that you've entered doesn't match any account. Sign up for an account.

it should be updated to 
"The email address/phone number that you've entered doesn't match any account. Sign up for an account."

**Comment by kshitijbhardwaj** [comment]
Message is coming from backend. @anmoldeep0123  pease handle

**Comment by theheapdump** [comment]
phone number feature is not there - it's a backlog

**Comment by bevanamit** [comment]
Then we should change label to have Email only

**Comment by theheapdump** [comment]
@kshitijbhardwaj, for now, login with email only -> please remove all phone number text

**Comment by bevanamit** [comment]
tested
