### ISSUE TITLE
Analysis: The prompt for Profile and Broker when the User logs in the 2nd time is Not appearing good

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#66]
The prompt for Profile and Broker when the User logs in the 2nd time is Not appearing good.

Maybe because it appears as a Page rather than a prompt message.  @anmoldeep0123 @kshitijbhardwaj  what do you think ? try thinking if You are the Customer what would you like

**Comment by bevanamit** [comment]
Maybe blur the background 50% and see how it will look, or the design of the prompt itself that we are showing is not very good.

**Comment by theheapdump** [comment]
@kshitijbhardwaj  -  is this doable ??

**Comment by theheapdump** [comment]
@bevanamit
