### ISSUE TITLE
UI | Develop UI for skip profile -> skip broker -> login flow 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#68]
If the User has not configured Profile and Broker we give a message in Dashboard Screen with link to do so

Currently we are showing 
Hi User, You're logged into TradeGenie

**Comment by kshitijbhardwaj** [comment]
If user has not configured profile or broker we are always taking him to profile or broker page after his login. He can do that then. I don't think there is any need to do anything else.
@bevanamit @anmoldeep0123  Please comment

**Comment by theheapdump** [comment]
the state will handle it . that's right . 

The user will not be able to land to the dashboard ever unless he completes the flow.

You can close this .If still there is a confusion -> we can have a call or close.

**Comment by bevanamit** [comment]
oh ok...but the user if he skips profile and broker and is logged in ... how to update the details ? @anmoldeep0123 @kshitijbhardwaj

**Comment by theheapdump** [comment]
we haven't developed that page yet . but it has to be a new UI . @kshitijbhardwaj

**Comment by bevanamit** [comment]
@anmoldeep0123 is this done ?

**Comment by theheapdump** [comment]
> @anmoldeep0123 is this done ?

It's by khitij @kshitijbhardwaj

**Comment by kshitijbhardwaj** [comment]
Closing this issue as it will be handled with development of #130. In profile settings page we will show his current configs and also provide edit options
