### ISSUE TITLE
Bug: If the User click Skip on Profile Information Page by mistake there is no way for him/her to go back to Page from Register Page

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#70]
If the User click Skip on Profile Information Page by mistake there is no way for him/her to go back to Page from Register Page.

Maybe a "BACK" with an Arrow, like "<--" would be good

**Comment by kshitijbhardwaj** [comment]
He can use browser back button to do so.

**Comment by kshitijbhardwaj** [comment]
he can use back button always. What is the need to give a back button specifically.

**Comment by theheapdump** [comment]
@bevanamit
