### ISSUE TITLE
Bug: Client ID text box in Register Screen should show the Respective Broker name 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#71]
Currently Client Id shows "Enter Client Id", it should be more informative, we should show "Enter <Broker> Broker Client ID"

**Comment by kshitijbhardwaj** [comment]
Fixed

**Comment by bevanamit** [comment]
![image](https://user-images.githubusercontent.com/5267251/99634423-80bf8d00-2a66-11eb-84ed-c5e850190d85.png)

@anmoldeep0123 : please provide your input as well

**Comment by theheapdump** [comment]
Zerodha can be removed. low priority .

**Comment by bevanamit** [comment]
Sorry forgot to mention @kshtj21@gmail.com <kshtj21@gmail.com> ... Please
add text Select Broker karke on the dropdown... Currently it is blank when
the screen is first visited.

**Comment by kshitijbhardwaj** [comment]
This issue was i think to add broker name in Client id text box. Now after adding that u are asking me to remove it again??
Please confirm

**Comment by bevanamit** [comment]
@kshitijbhardwaj you are right...it was to add Broker name in the textbox which is marked in the image.

please mark this fixed when done.

thanks
amit

**Comment by theheapdump** [comment]
not fixing
