### ISSUE TITLE
Bug: Clicking on Register button when we just Visit the Register Screen does not have any action

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#73]
Clicking on Register button when we just Visit the Register Screen does not have any action

Open URL, click on Register on Login Page
Then without filling anything Click on Register Button

There is no Action, it should show the information above has to be provided

**Comment by kshitijbhardwaj** [comment]
I have disabled the register button when there is nothing in the form or there is error in any of the fields. Untill and unless all info is filled correctly register button is not enabled.

**Comment by bevanamit** [comment]
Register button disabled by default
