### ISSUE TITLE
Bug: Cursor should be active on Phone number textbox on Register Screen + UI multiple issues

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#75]
Cursor should be active on Phone number textbox on Register Screen

**Comment by kshitijbhardwaj** [comment]
Done

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/98268443-87ec9280-1fb2-11eb-9ec7-0f46fe5f7718.png)

@kshitijbhardwaj  fix this as well

**Comment by theheapdump** [comment]
registered should be greyed out when error 
@kshitijbhardwaj  fix this also
![image](https://user-images.githubusercontent.com/7692754/98268645-c84c1080-1fb2-11eb-88fe-e8a96c9b2550.png)

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/98268828-ff222680-1fb2-11eb-888b-39c2810c6eab.png)

in this screen , first time after email registration - generate otp should not be there 
it gives a wrong picture 

OTP is already sent by backend 


@kshitijbhardwaj  @bevanamit

**Comment by theheapdump** [comment]
Send again is there - it's fine .... Generate OTP is not required 

thoughts @bevanamit

**Comment by theheapdump** [comment]
@kshitijbhardwaj 

![image](https://user-images.githubusercontent.com/7692754/98269131-66d87180-1fb3-11eb-8b8a-fdcf7a751ca1.png)


when 3 times OTP is sent. - send again is greyed out - some message is to be shown to the user -?? 
what is he expected to do next - try again later - ?? 

contact us ?? 

@bevanamit  thoughts ??

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/98269299-8ff90200-1fb3-11eb-9ac1-20e14c64ef15.png)


six digit code validation - 7 digits or more not allowed 

alphabets not allowed.

@bevanamit

**Comment by theheapdump** [comment]
![image](https://user-images.githubusercontent.com/7692754/98269521-d4849d80-1fb3-11eb-9299-12b2ece5b856.png)

add a limit on calling confirm otp -> it can be called any number of times , i think 3 is a good number .

@bevanamit  ??

**Comment by bevanamit** [comment]
> Send again is there - it's fine .... Generate OTP is not required
> 
> thoughts @bevanamit

i think i mentioned the same long back

**Comment by bevanamit** [comment]
Not resolved

**Comment by kshitijbhardwaj** [comment]
Fixed the issues

**Comment by theheapdump** [comment]
Closing as fixed .

**Comment by bevanamit** [comment]
Please mark issues fixed, I will test and mark completed

**Comment by theheapdump** [comment]
by mistake .!!!
