### ISSUE TITLE
Bug: Once the Text in Confirm password matches to Password the message "Password and Confirm password didn't match" should vanish

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#77]
Once the Text in Confirm password matches to Password the message "Password and Confirm password didn't match" should vanish

1. Go to register screen
2. fill in all details
3. fill in different password in confirm password, a message "Password and Confirm password didn't match" will be shown
4. Correct the text the message is still there, it should vanish

**Comment by theheapdump** [comment]
even i have faced this @kshitijbhardwaj

**Comment by kshitijbhardwaj** [comment]
Fixed

**Comment by bevanamit** [comment]
Issue fixed tested
