### ISSUE TITLE
QA : Install Mongo DB client software to connect to mongo and see DB for DB testing. 

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#78]

**Comment by theheapdump** [comment]
@bevanamit - please take care of this

**Comment by theheapdump** [comment]
mongo compass

**Comment by theheapdump** [comment]
@bevanamit  , please close this today. have the setup ready and close this.

**Comment by bevanamit** [comment]
Yes... Will complete

**Comment by bevanamit** [comment]
@anmoldeep0123 please share the URL to connect

**Comment by theheapdump** [comment]
mongodb://35.187.245.85:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false

**Comment by theheapdump** [comment]
@bevanamit

**Comment by bevanamit** [comment]
This is done.... I just need to use the url u provided... Will mark this in
max 2hours

**Comment by bevanamit** [comment]
Connection works
