### ISSUE TITLE
Bug: Send Again on Confirm OTP page should be corrected

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#80]
As of now the User can keep clicking the "Send Again" Link without any limit.

please add 30 second interval when the Page is shown first time and after 30 seconds enable it and Max retries will allow 3 times with 30 seconds interval. currently it is unlimited

**Comment by kshitijbhardwaj** [comment]
On clicking the send again the  button disappears for 1 min. One notification will come stating otp sent and try again for new otp after 1 min. It will me comeup again after 1 min depending on the number of clicks weather enabled or disabled. if clicked more than 3 times it will be disabled.

**Comment by bevanamit** [comment]
Tested
