### ISSUE TITLE
Migrate Kite Developer application from amazon to google cloud platform.

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#84]
Strategy

0. Initially we will move the Kite Developer to GCP completely
1. Shared db between gcp and az runtime.
2. Any server should be able to read token from db and start the runtime and run top gainers top losers feature.

**Comment by bevanamit** [comment]
i did not get what this means moving to GCP the kite developer

**Comment by theheapdump** [comment]
Old data :

redirect_uri : https://13.235.80.186:8080/kiteAndee/getRequestToken
postback_uri : https://13.235.80.186:8080/kiteAndee/postBack

new data : 
redirect_uri : https://35.187.245.85:8080/tb/ui/v1/kdev/XA1346/get
postback_uri : https://35.187.245.85:8080/tb/ui/v1/kdev/XA1346/back

**Comment by theheapdump** [comment]
@bevanamit - runtime from AZ to GCP through our new UI

**Comment by bevanamit** [comment]
Oh ok... Same folder structure to be maintained.

**Comment by theheapdump** [comment]
yes @bevanamit

**Comment by bevanamit** [comment]
@anmoldeep0123 I will be deleting and moving the folder structure completely to the GCP machine now, let me know if any concerns.

**Comment by theheapdump** [comment]
@bevanamit  NO
