### ISSUE TITLE
QA : database | user-session | session expiry testing 

### ISSUE THREAD

**Issue by theheapdump** [theheapdump/kite-webapp#90]
Objects in kiteandee.user_session table have 2  fields 
- expiry_time - this is user inactivity expiry 
- max_age - this is max_age of the cookie of TradeBull Session

we need to test session expiry based on both the above fields

**Comment by theheapdump** [comment]
kite/app/config/webgui.properties

pi.webgui.session.max-age=6h

pi.webgui.session.expiry-time=30

**Comment by theheapdump** [comment]
@bevanamit  test this with DB also 

table name is user_session

**Comment by bevanamit** [comment]
i need to test these properties

**Comment by bevanamit** [comment]
2 active issues open on this
pi.webgui.session.expiry-time works as expected
issue observed with pi.webgui.session.max-age which is raised


https://github.com/anmoldeep0123/kite-webapp/issues/150
https://github.com/anmoldeep0123/kite-webapp/issues/149
