### ISSUE TITLE
Bug: Not defined broker details, the login is redirecting to KITE with NA

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#91]
register new user, skip profile and broker...logout,...try login again with the new user

by default even if broker is not set there is a redirect to the  kite login
![image](https://user-images.githubusercontent.com/5267251/99394856-95384400-2905-11eb-80d6-0fd42a022ffd.png)

**Comment by theheapdump** [comment]
@bevanamit  please retest this .

**Comment by bevanamit** [comment]
fixed
