### ISSUE TITLE
Bug: Login with phone number does not work as expected

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#92]
register user
dont update profile and broker
logout
try using phone number to login

![image](https://user-images.githubusercontent.com/5267251/99395380-56ef5480-2906-11eb-8be8-21ac0170a87c.png)

**Comment by kshitijbhardwaj** [comment]
@anmoldeep0123  can u take care of it?

**Comment by theheapdump** [comment]
it's a backlog - will do

**Comment by theheapdump** [comment]
@bevanamit  - login with phonenumber is not supported yet - it will be in this release.

**Comment by theheapdump** [comment]
@bevanamit  - login with phonenumber is there now !!! 
please test

**Comment by bevanamit** [comment]
Oh ok.. Will do when I start

**Comment by bevanamit** [comment]
tested
