### ISSUE TITLE
Bug: Closing without confirming OTP and trying to login  next time lets t

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#95]
1. User open the Tradebull application
2. Click on Register
3. Provide details required, click on Register
4. On the OTP screen, close the window
5. Try logging in with the registered user

Expected
1. On login the OTP screen should be shown
2. The OTP should be confirmed and the next screens should be shown 

Actual
User is let in without OTP confirmation

**Comment by theheapdump** [comment]
@bevanamit Good catch - this is backend issue will fix this,

**Comment by bevanamit** [comment]
Not required, we need to ignore and not put these users to db

**Comment by theheapdump** [comment]
> Not required, we need to ignore and not put these users to db

that's a bad fix - user is put to DB on registration

**Comment by theheapdump** [comment]
it will be fixed as per the flow @bevanamit

**Comment by bevanamit** [comment]
Actually we need to remove such users from db... They can register again if
they really want to

**Comment by theheapdump** [comment]
that's why we have the state machine -

**Comment by theheapdump** [comment]
it will handle the flow

**Comment by bevanamit** [comment]
Ok

**Comment by theheapdump** [comment]
Speaking of this 
we have another test case @bevanamit 

a user - who registered - did not update OTP - came back and registered again - we should inform him - that he is already there in our DB

**Comment by bevanamit** [comment]
tested
