### ISSUE TITLE
Bug: Trying to create Already registered user again does not work as expected

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#98]
create a user, fill in all required details and logout
use that user to login, logout
Navigate to Register page and try using the same Email id and phone number for registration

Expected
When the user enters the email and phone number it should show that its already taken

Actual (image) - it shows OK message
![image](https://user-images.githubusercontent.com/5267251/99427304-40a7bf80-292b-11eb-9a8c-2accd9dbd868.png)

**Comment by kshitijbhardwaj** [comment]
@anmoldeep0123  Handle this in backend

**Comment by theheapdump** [comment]
good issue @bevanamit

**Comment by theheapdump** [comment]
Fixed in backend -> 
@kshitijbhardwaj  needs to fix in front end.
![Uploading image.png…]()

**Comment by theheapdump** [comment]
{
	"redirectTo": null,
	"status": "ERROR",
	"status_message": "User with Email Address anmoldeep0123@gmail.com already exists.",
	"response": null
}

**Comment by theheapdump** [comment]
Fixed @bevanamit

**Comment by bevanamit** [comment]
tested
![image](https://user-images.githubusercontent.com/5267251/99635565-2c1d1180-2a68-11eb-805d-29385df14e3a.png)
