### ISSUE TITLE
Bug: Have Links to Profile page and Broker page for modification as and when required . Duplicate of #130 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#99]
Have Links to Profile page and Broker page for modification as and when required

**Comment by kshitijbhardwaj** [comment]
@bevanamit  This will be implemented with profile setting page

**Comment by bevanamit** [comment]
Is this committed??

**Comment by bevanamit** [comment]
If this is not done yet, please assign once that is implemented

**Comment by kshitijbhardwaj** [comment]
No sir wo page bana hi nhi hai abhi will be handled with it.

**Comment by kshitijbhardwaj** [comment]
I think we can close this issue for now

**Comment by theheapdump** [comment]
@bevanamit  backlog

**Comment by theheapdump** [comment]
This is a duplicate of #130 . Closing this as duplicate
